name: autonoma
description: App para buscar as melhores pessoas autônomas prestadoras de serviços da sua região

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.1
  flutter_triple: ^3.0.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  cloud_firestore: ^4.9.1
  dartz: ^0.10.1
  flutter_chat_ui: ^1.6.9
  path: ^1.8.3
  image_picker: ^1.0.4
  image_cropper: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true


assets:
  - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

